apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
description: Cloud Deploy pipeline for Cloud Run
serialPipeline:
  stages:
    - targetId: run-target
      profiles: []

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-target
description: Cloud Run target for us-central1
run:
  location: projects/testing-practice-org/locations/us-central1 # <--- THIS MUST BE us-central1 NOW
