apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
description: Cloud Deploy pipeline for Cloud Run
serialPipeline:
  stages:
    - targetId: run-target
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-target
description: Deploy to Cloud Run in asia-south1
run:
  location: asia-south1
