apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
description: Cloud Deploy pipeline to Cloud Run
serialPipeline:
  stages:
    - targetId: run-target
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-target
description: Cloud Run deployment target
run:
  location: projects/testing-practice-org/locations/asia-south1
