steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/testing-practice-org/my-repo/my-app:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/testing-practice-org/my-repo/my-app:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'deploy',
      'releases',
      'create',
      'release-$SHORT_SHA',
      '--delivery-pipeline=cloud-run-pipeline',
      '--region=us-central1',
      '--images=my-app=us-central1-docker.pkg.dev/testing-practice-org/my-repo/my-app:$SHORT_SHA'
    ]
options:
  logging: CLOUD_LOGGING_ONLY
